/**
 * AFCON PAMOJA 2026
 * Ticketing configuration
 *
 * IMPORTANT:
 * Stadium geometry comes from old-index.html.
 * This file controls:
 *   - matches
 *   - ticket limits
 *   - pricing
 *   - Fan ID rules
 *   - fees
 */

window.TICKETING_DATA = {

  /* =========================================================
     TICKETING RULES
  ========================================================= */

  rules: {

    /* PAMOJA product rule */
    minimumTicketsPerOrder: 1,

    /* User-requested maximum */
    maximumTicketsPerOrder: 6,

    /*
     * Every ticket must have one Fan ID.
     * A Fan ID cannot be reused for another ticket
     * in the same match.
     */
    fanIdRequired: true,

    uniqueFanIdPerMatch: true,

    /*
     * Tickets are digital and personalized.
     */
    digitalOnly: true,
    personalized: true,

    /*
     * No stadium-door ticket sales.
     */
    stadiumSales: false,

    /*
     * Refund rule supplied for this product.
     */
    refundPolicy:
      'Refunds are available only when a match is officially cancelled by CAF.'
  },


  /* =========================================================
     SERVICE CHARGES
  ========================================================= */

  serviceLevyRate: 0.16,


  /* =========================================================
     PAYMENT METHODS
  ========================================================= */

  paymentMethods: [

    {
      id: 'visa',
      name: 'Visa',
      enabled: true
    },

    {
      id: 'mastercard',
      name: 'Mastercard',
      enabled: true
    }

  ],


  /* =========================================================
     MATCHES
  ========================================================= */

  matches: [

    {
      id: 'm1',

      home: 'Kenya 🇰🇪',
      away: 'Senegal 🇸🇳',

      stage: 'Grand Opening Match',
      stageKey: 'group',

      venueKey: 'kasarani',

      date: 'Fri, 18 Sep 2026',
      time: '20:00 EAT',

      capacity: 60000,

      occupiedSeats: 51240,

      stockStatus:
        '● High Demand - 85% Sold',

      stockColor:
        'text-amber-400 bg-amber-500/10 border-amber-500/30'
    },


    {
      id: 'm2',

      home: 'Nigeria 🇳🇬',
      away: 'Ivory Coast 🇨🇮',

      stage: 'Quarter-Final 1',
      stageKey: 'quarters',

      venueKey: 'nyayo',

      date: 'Sun, 20 Sep 2026',
      time: '17:00 EAT',

      capacity: 30000,

      occupiedSeats: 26800,

      stockStatus:
        '● VIP Only Remaining',

      stockColor:
        'text-orange-400 bg-orange-500/10 border-orange-500/30'
    },


    {
      id: 'm3',

      home: 'Morocco 🇲🇦',
      away: 'Egypt 🇪🇬',

      stage: 'Tournament Grand Final 🏆',
      stageKey: 'final',

      venueKey: 'eldoret',

      date: 'Sat, 26 Sep 2026',
      time: '21:00 EAT',

      capacity: 15000,

      occupiedSeats: 13800,

      stockStatus:
        '● Selling Fast (92%)',

      stockColor:
        'text-emerald-400 bg-emerald-500/10 border-emerald-500/30'
    }

  ],


  /* =========================================================
     VENUE PRICING
  ========================================================= */

  venues: {

    kasarani: {

      name:
        'Moi International Sports Centre, Kasarani',

      city:
        'Nairobi, Kenya',

      capacity:
        60000,

      description:
        'A large multi-tier stadium with premium, Category 1, Category 2 and Category 3 seating.',

      /*
       * These prices are attached to the section/category,
       * NOT generated by the map.
       */

      pricing: {

        vvip: 5000,
        cat1: 3000,
        cat2: 1800,
        cat3: 1000

      }

    },


    nyayo: {

      name:
        'Nyayo National Stadium',

      city:
        'Nairobi, Kenya',

      capacity:
        30000,

      description:
        'A compact stadium with premium west-side seating and Category 2 and Category 3 sections.',

      pricing: {

        vvip: 5000,
        cat1: 3500,
        cat2: 1800,
        cat3: 1000

      }

    },


    eldoret: {

      name:
        'Kipchoge Keino Stadium',

      city:
        'Eldoret, Kenya',

      capacity:
        15000,

      description:
        'A smaller stadium offering an intimate match-day experience.',

      pricing: {

        vvip: 4000,
        cat1: 2500,
        cat2: 1400,
        cat3: 800

      }

    }

  }

};


/* =============================================================
   HELPERS
============================================================= */

window.getMatch = function(matchId) {

  return window.TICKETING_DATA.matches.find(
    match => match.id === matchId
  );

};


window.getVenue = function(match) {

  if (!match) {
    return null;
  }

  return window.TICKETING_DATA.venues[
    match.venueKey
  ];

};


window.getVenuePricing = function(match) {

  const venue =
    window.getVenue(match);

  return venue
    ? venue.pricing
    : {};

};


window.getTicketPrice = function(
  match,
  tier
) {

  const pricing =
    window.getVenuePricing(match);

  return Number(
    pricing[tier] || 0
  );

};


window.money = function(value) {

  return `KES ${Number(value || 0)
    .toLocaleString('en-KE')}`;

};